code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension nicolaspolomack.epitech-c-cpp-headers
code --install-extension codezombiech.gitignore
code --install-extension donjayamanne.git-extension-pack
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension alefragnani.project-manager
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension natqe.reload
code --install-extension nhoizey.gremlins
code --install-extension shardulm94.trailing-spaces
code --install-extension usernamehw.errorlens
code --install-extension vs-publisher-1448185.keyoti-changeallendoflinesequence
code --install-extension ziyasal.vscode-open-in-github